import express from 'express';
import helmet from 'helmet';
import session from 'express-session';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import mysql from 'mysql2/promise';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaults } from './lib/status.js';
import { parameterStatus } from './lib/status.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const port=Number(process.env.PORT||3000);

// Database connection for the deployed monitoring database.
// Keep these values in one place so the runtime does not depend on a local .env file.
const databaseConfig={
  host:'141.148.197.200',
  port:3307,
  user:'project',
  password:'Dulina123',
  database:'generator_monitoring',
  waitForConnections:true,
  connectionLimit:5,
  connectTimeout:10000,
};
const pool=mysql.createPool(databaseConfig);
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json()); app.use(express.urlencoded({extended:false})); app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}}));
app.use(rateLimit({windowMs:15*60*1000,limit:120,standardHeaders:true,legacyHeaders:false,skip:req=>req.method==='GET'}));
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'Authentication required'});
app.post('/api/login',async(req,res)=>{try{const identifier=String(req.body.username||'').trim(); const password=String(req.body.password||''); if(!identifier||!password)return res.status(400).json({error:'Enter username and password.'}); const [rows]=await pool.query('SELECT user_id,name,email,password_hash,role FROM users WHERE email=? OR name=? LIMIT 1',[identifier,identifier]); const user=rows[0]; if(!user||!await bcrypt.compare(password,user.password_hash))return res.status(401).json({error:'Invalid username or password.'}); req.session.user={id:user.user_id,name:user.name,email:user.email,role:user.role}; res.json({user:req.session.user});}catch(e){console.error('Login failed', {code:e.code||'UNKNOWN',errno:e.errno,sqlState:e.sqlState});res.status(503).json({error:'Database unavailable. Check the server connection.'})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true}))); app.get('/api/session',(req,res)=>res.json({user:req.session.user||null}));
app.get('/api/config',auth,async(req,res)=>{try{const [rows]=await pool.query('SELECT parameter,warning_min,warning_max,critical_min,critical_max,enabled FROM maintenance_config WHERE enabled=1'); res.json({rows,defaults});}catch(e){res.status(503).json({error:'Configuration unavailable.'})}});
app.put('/api/config',auth,async(req,res)=>{if(req.session.user.role!=='admin')return res.status(403).json({error:'Only administrators can change thresholds.'});try{const {parameter,warning_min,warning_max,critical_min,critical_max}=req.body;if(!['temperature','voltage','frequency','fuel'].includes(parameter))return res.status(400).json({error:'Invalid parameter.'});await pool.query('UPDATE maintenance_config SET warning_min=?,warning_max=?,critical_min=?,critical_max=?,enabled=1,updated_at=NOW() WHERE parameter=?',[warning_min||null,warning_max||null,critical_min||null,critical_max||null,parameter]);res.json({ok:true});}catch(e){res.status(503).json({error:'Unable to save configuration.'})}});
app.get('/api/generators',auth,async(req,res)=>{try{const [rows]=await pool.query('SELECT generator_id,name,serial_no,location,rated_capacity_kva,install_date FROM generators ORDER BY name');res.json({rows,telemetryAvailable:false});}catch(e){res.status(503).json({error:'Generators unavailable.'})}});
app.get('/api/generators/:id/latest',auth,async(req,res)=>{try{const [rows]=await pool.query('SELECT status,voltage,current,frequency,temperature,fuel_level,runtime_seconds,recorded_at FROM generator_readings WHERE generator_id=? ORDER BY recorded_at DESC LIMIT 1',[req.params.id]);res.json({reading:rows[0]||null});}catch(e){res.status(503).json({error:'Telemetry unavailable.'})}});
app.get('/api/notifications',auth,async(req,res)=>{try{const [rows]=await pool.query('SELECT n.notification_id,n.title,n.detail,n.status,n.created_at,g.name AS generator_name FROM notifications n JOIN generators g ON g.generator_id=n.generator_id ORDER BY n.created_at DESC LIMIT 100');res.json({rows});}catch(e){res.status(503).json({error:'Notifications unavailable.'})}});
app.post('/api/generators',auth,async(req,res)=>{if(req.session.user.role!=='admin')return res.status(403).json({error:'Only administrators can add generators.'});try{const {name,serial_no,location,rated_capacity_kva,install_date}=req.body;if(!name||!serial_no)return res.status(400).json({error:'Name and serial number are required.'});const [r]=await pool.query('INSERT INTO generators (name,serial_no,location,rated_capacity_kva,install_date) VALUES (?,?,?,?,?)',[name,serial_no,location||null,rated_capacity_kva||null,install_date||null]);res.status(201).json({generator_id:r.insertId});}catch(e){res.status(e.code==='ER_DUP_ENTRY'?409:503).json({error:e.code==='ER_DUP_ENTRY'?'Serial number already exists.':'Unable to add generator.'})}});
app.post('/api/generators/:id/readings',auth,async(req,res)=>{try{const b=req.body;const fields=['status','voltage','current','frequency','temperature','fuel_level','runtime_seconds'];if(!fields.every(k=>b[k]!==undefined))return res.status(400).json({error:'All reading fields are required.'});await pool.query('INSERT INTO generator_readings (generator_id,status,voltage,current,frequency,temperature,fuel_level,runtime_seconds) VALUES (?,?,?,?,?,?,?,?)',[req.params.id,b.status,b.voltage,b.current,b.frequency,b.temperature,b.fuel_level,b.runtime_seconds]);const [cfg]=await pool.query('SELECT parameter,warning_min,warning_max,critical_min,critical_max FROM maintenance_config WHERE enabled=1');const limits={...defaults};for(const x of cfg){if(x.parameter==='temperature'){limits.temperatureWarning=Number(x.warning_min);limits.temperatureCritical=Number(x.critical_max)}if(x.parameter==='fuel'){limits.fuelWarning=Number(x.warning_min);limits.fuelCritical=Number(x.critical_min)}if(x.parameter==='voltage'){limits.voltageWarningMin=Number(x.warning_min);limits.voltageWarningMax=Number(x.warning_max);limits.voltageCriticalMin=Number(x.critical_min);limits.voltageCriticalMax=Number(x.critical_max)}if(x.parameter==='frequency'){limits.frequencyWarningMin=Number(x.warning_min);limits.frequencyWarningMax=Number(x.warning_max);limits.frequencyCriticalMin=Number(x.critical_min);limits.frequencyCriticalMax=Number(x.critical_max)}}const checks=[['High temperature','temperature',b.temperature,'Temperature'],['Voltage out of range','voltage',b.voltage,'Voltage'],['Frequency out of range','frequency',b.frequency,'Frequency'],['Low fuel','fuel',b.fuel_level,'Fuel']];for(const [title,key,value,label] of checks){const status=parameterStatus(key,value,limits);if(status==='warning'||status==='critical')await pool.query('INSERT INTO notifications (generator_id,title,detail,status) VALUES (?,?,?,?)',[req.params.id,title,`${label}: ${value} (${status})`,'active']);}res.status(201).json({ok:true});}catch(e){res.status(503).json({error:'Unable to save reading.'})}});
app.get('/api/users',auth,async(req,res)=>{try{const [rows]=await pool.query('SELECT user_id,name,email,role,created_at FROM users ORDER BY name');res.json({rows});}catch(e){res.status(503).json({error:'Users unavailable.'})}});
app.post('/api/users',auth,async(req,res)=>{if(req.session.user.role!=='admin')return res.status(403).json({error:'Only administrators can create users.'});try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),role=String(req.body.role||'viewer');if(!name||!email||password.length<8||!['admin','operator','viewer'].includes(role))return res.status(400).json({error:'Name, email, valid role, and a password of at least 8 characters are required.'});const hash=await bcrypt.hash(password,12);await pool.query('INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)',[name,email,hash,role]);res.status(201).json({ok:true});}catch(e){res.status(e.code==='ER_DUP_ENTRY'?409:503).json({error:e.code==='ER_DUP_ENTRY'?'That email is already in use.':'Unable to create user.'})}});
app.get('/favicon.ico',(req,res)=>res.status(204).end()); app.use(express.static(path.join(root,'public'))); app.use((req,res)=>res.sendFile(path.join(root,'public/index.html'))); app.listen(port,()=>console.log(`Generator System listening on http://localhost:${port}`));
